give @a minecraft:acacia_boat 1
give @a minecraft:acacia_button 1
give @a minecraft:acacia_chest_boat 1
give @a minecraft:acacia_door 1
give @a minecraft:acacia_fence 1
give @a minecraft:acacia_fence_gate 1
give @a minecraft:acacia_leaves 1
give @a minecraft:acacia_log 1
give @a minecraft:acacia_planks 1
give @a minecraft:acacia_pressure_plate 1
give @a minecraft:acacia_sapling 1
give @a minecraft:acacia_sign 1
give @a minecraft:acacia_slab 1
give @a minecraft:acacia_stairs 1
give @a minecraft:acacia_trapdoor 1
give @a minecraft:acacia_wood 1
give @a minecraft:activator_rail 1
give @a minecraft:allay_spawn_egg 1
give @a minecraft:allium 1
give @a minecraft:amethyst_block 1
give @a minecraft:amethyst_cluster 1
give @a minecraft:amethyst_shard 1
give @a minecraft:ancient_debris 1
give @a minecraft:andesite 1
give @a minecraft:andesite_slab 1
give @a minecraft:andesite_stairs 1
give @a minecraft:andesite_wall 1
give @a minecraft:anvil 1
give @a minecraft:apple 1
give @a minecraft:armor_stand 1
give @a minecraft:arrow 1
give @a minecraft:axolotl_bucket 1
give @a minecraft:axolotl_spawn_egg 1
give @a minecraft:azalea 1
give @a minecraft:azalea_leaves 1
give @a minecraft:azure_bluet 1
give @a minecraft:baked_potato 1
give @a minecraft:bamboo 1
give @a minecraft:barrel 1
give @a minecraft:barrier 1
give @a minecraft:basalt 1
give @a minecraft:bat_spawn_egg 1
give @a minecraft:beacon 1
give @a minecraft:bedrock 1
give @a minecraft:bee_nest 1
give @a minecraft:bee_spawn_egg 1
give @a minecraft:beef 1
give @a minecraft:beehive 1
give @a minecraft:beetroot 1
give @a minecraft:beetroot_seeds 1
give @a minecraft:beetroot_soup 1
give @a minecraft:bell 1
give @a minecraft:big_dripleaf 1
give @a minecraft:birch_boat 1
give @a minecraft:birch_button 1
give @a minecraft:birch_chest_boat 1
give @a minecraft:birch_door 1
give @a minecraft:birch_fence 1
give @a minecraft:birch_fence_gate 1
give @a minecraft:birch_leaves 1
give @a minecraft:birch_log 1
give @a minecraft:birch_planks 1
give @a minecraft:birch_pressure_plate 1
give @a minecraft:birch_sapling 1
give @a minecraft:birch_sign 1
give @a minecraft:birch_slab 1
give @a minecraft:birch_stairs 1
give @a minecraft:birch_trapdoor 1
give @a minecraft:birch_wood 1
give @a minecraft:black_banner 1
give @a minecraft:black_bed 1
give @a minecraft:black_candle 1
give @a minecraft:black_carpet 1
give @a minecraft:black_concrete 1
give @a minecraft:black_concrete_powder 1
give @a minecraft:black_dye 1
give @a minecraft:black_glazed_terracotta 1
give @a minecraft:black_shulker_box 1
give @a minecraft:black_stained_glass 1
give @a minecraft:black_stained_glass_pane 1
give @a minecraft:black_terracotta 1
give @a minecraft:black_wool 1
give @a minecraft:blackstone 1
give @a minecraft:blackstone_slab 1
give @a minecraft:blackstone_stairs 1
give @a minecraft:blackstone_wall 1
give @a minecraft:blast_furnace 1
give @a minecraft:blaze_powder 1
give @a minecraft:blaze_rod 1
give @a minecraft:blaze_spawn_egg 1
give @a minecraft:blue_banner 1
give @a minecraft:blue_bed 1
give @a minecraft:blue_candle 1
give @a minecraft:blue_carpet 1
give @a minecraft:blue_concrete 1
give @a minecraft:blue_concrete_powder 1
give @a minecraft:blue_dye 1
give @a minecraft:blue_glazed_terracotta 1
give @a minecraft:blue_ice 1
give @a minecraft:blue_orchid 1
give @a minecraft:blue_shulker_box 1
give @a minecraft:blue_stained_glass 1
give @a minecraft:blue_stained_glass_pane 1
give @a minecraft:blue_terracotta 1
give @a minecraft:blue_wool 1
give @a minecraft:bone 1
give @a minecraft:bone_block 1
give @a minecraft:bone_meal 1
give @a minecraft:book 1
give @a minecraft:bookshelf 1
give @a minecraft:bow 1
give @a minecraft:bowl 1
give @a minecraft:brain_coral 1
give @a minecraft:brain_coral_block 1
give @a minecraft:brain_coral_fan 1
give @a minecraft:bread 1
give @a minecraft:brewing_stand 1
give @a minecraft:brick 1
give @a minecraft:brick_slab 1
give @a minecraft:brick_stairs 1
give @a minecraft:brick_wall 1
give @a minecraft:bricks 1
give @a minecraft:brown_banner 1
give @a minecraft:brown_bed 1
give @a minecraft:brown_candle 1
give @a minecraft:brown_carpet 1
give @a minecraft:brown_concrete 1
give @a minecraft:brown_concrete_powder 1
give @a minecraft:brown_dye 1
give @a minecraft:brown_glazed_terracotta 1
give @a minecraft:brown_mushroom 1
give @a minecraft:brown_mushroom_block 1
give @a minecraft:brown_shulker_box 1
give @a minecraft:brown_stained_glass 1
give @a minecraft:brown_stained_glass_pane 1
give @a minecraft:brown_terracotta 1
give @a minecraft:brown_wool 1
give @a minecraft:bubble_coral 1
give @a minecraft:bubble_coral_block 1
give @a minecraft:bubble_coral_fan 1
give @a minecraft:bucket 1
give @a minecraft:budding_amethyst 1
give @a minecraft:bundle 1
give @a minecraft:cactus 1
give @a minecraft:cake 1
give @a minecraft:calcite 1
give @a minecraft:campfire 1
give @a minecraft:candle 1
give @a minecraft:carrot 1
give @a minecraft:carrot_on_a_stick 1
give @a minecraft:cartography_table 1
give @a minecraft:carved_pumpkin 1
give @a minecraft:cat_spawn_egg 1
give @a minecraft:cauldron 1
give @a minecraft:cave_spider_spawn_egg 1
give @a minecraft:chain 1
give @a minecraft:chain_command_block 1
give @a minecraft:chainmail_boots 1
give @a minecraft:chainmail_chestplate 1
give @a minecraft:chainmail_helmet 1
give @a minecraft:chainmail_leggings 1
give @a minecraft:charcoal 1
give @a minecraft:chest 1
give @a minecraft:chest_minecart 1
give @a minecraft:chicken 1
give @a minecraft:chicken_spawn_egg 1
give @a minecraft:chipped_anvil 1
give @a minecraft:chiseled_deepslate 1
give @a minecraft:chiseled_nether_bricks 1
give @a minecraft:chiseled_polished_blackstone 1
give @a minecraft:chiseled_quartz_block 1
give @a minecraft:chiseled_red_sandstone 1
give @a minecraft:chiseled_sandstone 1
give @a minecraft:chiseled_stone_bricks 1
give @a minecraft:chorus_flower 1
give @a minecraft:chorus_fruit 1
give @a minecraft:chorus_plant 1
give @a minecraft:clay 1
give @a minecraft:clay_ball 1
give @a minecraft:clock 1
give @a minecraft:coal 1
give @a minecraft:coal_block 1
give @a minecraft:coal_ore 1
give @a minecraft:coarse_dirt 1
give @a minecraft:cobbled_deepslate 1
give @a minecraft:cobbled_deepslate_slab 1
give @a minecraft:cobbled_deepslate_stairs 1
give @a minecraft:cobbled_deepslate_wall 1
give @a minecraft:cobblestone 1
give @a minecraft:cobblestone_slab 1
give @a minecraft:cobblestone_stairs 1
give @a minecraft:cobblestone_wall 1
give @a minecraft:cobweb 1
give @a minecraft:cocoa_beans 1
give @a minecraft:cod 1
give @a minecraft:cod_bucket 1
give @a minecraft:cod_spawn_egg 1
give @a minecraft:command_block 1
give @a minecraft:command_block_minecart 1
give @a minecraft:comparator 1
give @a minecraft:compass 1
give @a minecraft:composter 1
give @a minecraft:conduit 1
give @a minecraft:cooked_beef 1
give @a minecraft:cooked_chicken 1
give @a minecraft:cooked_cod 1
give @a minecraft:cooked_mutton 1
give @a minecraft:cooked_porkchop 1
give @a minecraft:cooked_rabbit 1
give @a minecraft:cooked_salmon 1
give @a minecraft:cookie 1
give @a minecraft:copper_block 1
give @a minecraft:copper_ingot 1
give @a minecraft:copper_ore 1
give @a minecraft:cornflower 1
give @a minecraft:cow_spawn_egg 1
give @a minecraft:cracked_deepslate_bricks 1
give @a minecraft:cracked_deepslate_tiles 1
give @a minecraft:cracked_nether_bricks 1
give @a minecraft:cracked_polished_blackstone_bricks 1
give @a minecraft:cracked_stone_bricks 1
give @a minecraft:crafting_table 1
give @a minecraft:creeper_banner_pattern 1
give @a minecraft:creeper_head 1
give @a minecraft:creeper_spawn_egg 1
give @a minecraft:crimson_button 1
give @a minecraft:crimson_door 1
give @a minecraft:crimson_fence 1
give @a minecraft:crimson_fence_gate 1
give @a minecraft:crimson_fungus 1
give @a minecraft:crimson_hyphae 1
give @a minecraft:crimson_nylium 1
give @a minecraft:crimson_planks 1
give @a minecraft:crimson_pressure_plate 1
give @a minecraft:crimson_roots 1
give @a minecraft:crimson_sign 1
give @a minecraft:crimson_slab 1
give @a minecraft:crimson_stairs 1
give @a minecraft:crimson_stem 1
give @a minecraft:crimson_trapdoor 1
give @a minecraft:crossbow 1
give @a minecraft:crying_obsidian 1
give @a minecraft:cut_copper 1
give @a minecraft:cut_copper_slab 1
give @a minecraft:cut_copper_stairs 1
give @a minecraft:cut_red_sandstone 1
give @a minecraft:cut_red_sandstone_slab 1
give @a minecraft:cut_sandstone 1
give @a minecraft:cut_sandstone_slab 1
give @a minecraft:cyan_banner 1
give @a minecraft:cyan_bed 1
give @a minecraft:cyan_candle 1
give @a minecraft:cyan_carpet 1
give @a minecraft:cyan_concrete 1
give @a minecraft:cyan_concrete_powder 1
give @a minecraft:cyan_dye 1
give @a minecraft:cyan_glazed_terracotta 1
give @a minecraft:cyan_shulker_box 1
give @a minecraft:cyan_stained_glass 1
give @a minecraft:cyan_stained_glass_pane 1
give @a minecraft:cyan_terracotta 1
give @a minecraft:cyan_wool 1
give @a minecraft:damaged_anvil 1
give @a minecraft:dandelion 1
give @a minecraft:dark_oak_boat 1
give @a minecraft:dark_oak_button 1
give @a minecraft:dark_oak_chest_boat 1
give @a minecraft:dark_oak_door 1
give @a minecraft:dark_oak_fence 1
give @a minecraft:dark_oak_fence_gate 1
give @a minecraft:dark_oak_leaves 1
give @a minecraft:dark_oak_log 1
give @a minecraft:dark_oak_planks 1
give @a minecraft:dark_oak_pressure_plate 1
give @a minecraft:dark_oak_sapling 1
give @a minecraft:dark_oak_sign 1
give @a minecraft:dark_oak_slab 1
give @a minecraft:dark_oak_stairs 1
give @a minecraft:dark_oak_trapdoor 1
give @a minecraft:dark_oak_wood 1
give @a minecraft:dark_prismarine 1
give @a minecraft:dark_prismarine_slab 1
give @a minecraft:dark_prismarine_stairs 1
give @a minecraft:daylight_detector 1
give @a minecraft:dead_brain_coral 1
give @a minecraft:dead_brain_coral_block 1
give @a minecraft:dead_brain_coral_fan 1
give @a minecraft:dead_bubble_coral 1
give @a minecraft:dead_bubble_coral_block 1
give @a minecraft:dead_bubble_coral_fan 1
give @a minecraft:dead_bush 1
give @a minecraft:dead_fire_coral 1
give @a minecraft:dead_fire_coral_block 1
give @a minecraft:dead_fire_coral_fan 1
give @a minecraft:dead_horn_coral 1
give @a minecraft:dead_horn_coral_block 1
give @a minecraft:dead_horn_coral_fan 1
give @a minecraft:dead_tube_coral 1
give @a minecraft:dead_tube_coral_block 1
give @a minecraft:dead_tube_coral_fan 1
give @a minecraft:debug_stick 1
give @a minecraft:deepslate 1
give @a minecraft:deepslate_brick_slab 1
give @a minecraft:deepslate_brick_stairs 1
give @a minecraft:deepslate_brick_wall 1
give @a minecraft:deepslate_bricks 1
give @a minecraft:deepslate_coal_ore 1
give @a minecraft:deepslate_copper_ore 1
give @a minecraft:deepslate_diamond_ore 1
give @a minecraft:deepslate_emerald_ore 1
give @a minecraft:deepslate_gold_ore 1
give @a minecraft:deepslate_iron_ore 1
give @a minecraft:deepslate_lapis_ore 1
give @a minecraft:deepslate_redstone_ore 1
give @a minecraft:deepslate_tile_slab 1
give @a minecraft:deepslate_tile_stairs 1
give @a minecraft:deepslate_tile_wall 1
give @a minecraft:deepslate_tiles 1
give @a minecraft:detector_rail 1
give @a minecraft:diamond 1
give @a minecraft:diamond_axe 1
give @a minecraft:diamond_block 1
give @a minecraft:diamond_boots 1
give @a minecraft:diamond_chestplate 1
give @a minecraft:diamond_helmet 1
give @a minecraft:diamond_hoe 1
give @a minecraft:diamond_horse_armor 1
give @a minecraft:diamond_leggings 1
give @a minecraft:diamond_ore 1
give @a minecraft:diamond_pickaxe 1
give @a minecraft:diamond_shovel 1
give @a minecraft:diamond_sword 1
give @a minecraft:diorite 1
give @a minecraft:diorite_slab 1
give @a minecraft:diorite_stairs 1
give @a minecraft:diorite_wall 1
give @a minecraft:dirt 1
give @a minecraft:dirt_path 1
give @a minecraft:disc_fragment_5 1
give @a minecraft:dispenser 1
give @a minecraft:dolphin_spawn_egg 1
give @a minecraft:donkey_spawn_egg 1
give @a minecraft:dragon_breath 1
give @a minecraft:dragon_egg 1
give @a minecraft:dragon_head 1
give @a minecraft:dried_kelp 1
give @a minecraft:dried_kelp_block 1
give @a minecraft:dripstone_block 1
give @a minecraft:dropper 1
give @a minecraft:drowned_spawn_egg 1
give @a minecraft:echo_shard 1
give @a minecraft:egg 1
give @a minecraft:elder_guardian_spawn_egg 1
give @a minecraft:elytra 1
give @a minecraft:emerald 1
give @a minecraft:emerald_block 1
give @a minecraft:emerald_ore 1
give @a minecraft:enchanted_book 1
give @a minecraft:enchanted_golden_apple 1
give @a minecraft:enchanting_table 1
give @a minecraft:end_crystal 1
give @a minecraft:end_portal_frame 1
give @a minecraft:end_rod 1
give @a minecraft:end_stone 1
give @a minecraft:end_stone_brick_slab 1
give @a minecraft:end_stone_brick_stairs 1
give @a minecraft:end_stone_brick_wall 1
give @a minecraft:end_stone_bricks 1
give @a minecraft:ender_chest 1
give @a minecraft:ender_eye 1
give @a minecraft:ender_pearl 1
give @a minecraft:enderman_spawn_egg 1
give @a minecraft:endermite_spawn_egg 1
give @a minecraft:evoker_spawn_egg 1
give @a minecraft:experience_bottle 1
give @a minecraft:exposed_copper 1
give @a minecraft:exposed_cut_copper 1
give @a minecraft:exposed_cut_copper_slab 1
give @a minecraft:exposed_cut_copper_stairs 1
give @a minecraft:farmland 1
give @a minecraft:feather 1
give @a minecraft:fermented_spider_eye 1
give @a minecraft:fern 1
give @a minecraft:filled_map 1
give @a minecraft:fire_charge 1
give @a minecraft:fire_coral 1
give @a minecraft:fire_coral_block 1
give @a minecraft:fire_coral_fan 1
give @a minecraft:firework_rocket 1
give @a minecraft:firework_star 1
give @a minecraft:fishing_rod 1
give @a minecraft:fletching_table 1
give @a minecraft:flint 1
give @a minecraft:flint_and_steel 1
give @a minecraft:flower_banner_pattern 1
give @a minecraft:flower_pot 1
give @a minecraft:flowering_azalea 1
give @a minecraft:flowering_azalea_leaves 1
give @a minecraft:fox_spawn_egg 1
give @a minecraft:frog_spawn_egg 1
give @a minecraft:frogspawn 1
give @a minecraft:furnace 1
give @a minecraft:furnace_minecart 1
give @a minecraft:ghast_spawn_egg 1
give @a minecraft:ghast_tear 1
give @a minecraft:gilded_blackstone 1
give @a minecraft:glass 1
give @a minecraft:glass_bottle 1
give @a minecraft:glass_pane 1
give @a minecraft:glistering_melon_slice 1
give @a minecraft:globe_banner_pattern 1
give @a minecraft:glow_berries 1
give @a minecraft:glow_ink_sac 1
give @a minecraft:glow_item_frame 1
give @a minecraft:glow_lichen 1
give @a minecraft:glow_squid_spawn_egg 1
give @a minecraft:glowstone 1
give @a minecraft:glowstone_dust 1
give @a minecraft:goat_horn 1
give @a minecraft:goat_spawn_egg 1
give @a minecraft:gold_block 1
give @a minecraft:gold_ingot 1
give @a minecraft:gold_nugget 1
give @a minecraft:gold_ore 1
give @a minecraft:golden_apple 1
give @a minecraft:golden_axe 1
give @a minecraft:golden_boots 1
give @a minecraft:golden_carrot 1
give @a minecraft:golden_chestplate 1
give @a minecraft:golden_helmet 1
give @a minecraft:golden_hoe 1
give @a minecraft:golden_horse_armor 1
give @a minecraft:golden_leggings 1
give @a minecraft:golden_pickaxe 1
give @a minecraft:golden_shovel 1
give @a minecraft:golden_sword 1
give @a minecraft:granite 1
give @a minecraft:granite_slab 1
give @a minecraft:granite_stairs 1
give @a minecraft:granite_wall 1
give @a minecraft:grass 1
give @a minecraft:grass_block 1
give @a minecraft:gravel 1
give @a minecraft:gray_banner 1
give @a minecraft:gray_bed 1
give @a minecraft:gray_candle 1
give @a minecraft:gray_carpet 1
give @a minecraft:gray_concrete 1
give @a minecraft:gray_concrete_powder 1
give @a minecraft:gray_dye 1
give @a minecraft:gray_glazed_terracotta 1
give @a minecraft:gray_shulker_box 1
give @a minecraft:gray_stained_glass 1
give @a minecraft:gray_stained_glass_pane 1
give @a minecraft:gray_terracotta 1
give @a minecraft:gray_wool 1
give @a minecraft:green_banner 1
give @a minecraft:green_bed 1
give @a minecraft:green_candle 1
give @a minecraft:green_carpet 1
give @a minecraft:green_concrete 1
give @a minecraft:green_concrete_powder 1
give @a minecraft:green_dye 1
give @a minecraft:green_glazed_terracotta 1
give @a minecraft:green_shulker_box 1
give @a minecraft:green_stained_glass 1
give @a minecraft:green_stained_glass_pane 1
give @a minecraft:green_terracotta 1
give @a minecraft:green_wool 1
give @a minecraft:grindstone 1
give @a minecraft:guardian_spawn_egg 1
give @a minecraft:gunpowder 1
give @a minecraft:hanging_roots 1
give @a minecraft:hay_block 1
give @a minecraft:heart_of_the_sea 1
give @a minecraft:heavy_weighted_pressure_plate 1
give @a minecraft:hoglin_spawn_egg 1
give @a minecraft:honey_block 1
give @a minecraft:honey_bottle 1
give @a minecraft:honeycomb 1
give @a minecraft:honeycomb_block 1
give @a minecraft:hopper 1
give @a minecraft:hopper_minecart 1
give @a minecraft:horn_coral 1
give @a minecraft:horn_coral_block 1
give @a minecraft:horn_coral_fan 1
give @a minecraft:horse_spawn_egg 1
give @a minecraft:husk_spawn_egg 1
give @a minecraft:ice 1
give @a minecraft:infested_chiseled_stone_bricks 1
give @a minecraft:infested_cobblestone 1
give @a minecraft:infested_cracked_stone_bricks 1
give @a minecraft:infested_deepslate 1
give @a minecraft:infested_mossy_stone_bricks 1
give @a minecraft:infested_stone 1
give @a minecraft:infested_stone_bricks 1
give @a minecraft:ink_sac 1
give @a minecraft:iron_axe 1
give @a minecraft:iron_bars 1
give @a minecraft:iron_block 1
give @a minecraft:iron_boots 1
give @a minecraft:iron_chestplate 1
give @a minecraft:iron_door 1
give @a minecraft:iron_helmet 1
give @a minecraft:iron_hoe 1
give @a minecraft:iron_horse_armor 1
give @a minecraft:iron_ingot 1
give @a minecraft:iron_leggings 1
give @a minecraft:iron_nugget 1
give @a minecraft:iron_ore 1
give @a minecraft:iron_pickaxe 1
give @a minecraft:iron_shovel 1
give @a minecraft:iron_sword 1
give @a minecraft:iron_trapdoor 1
give @a minecraft:item_frame 1
give @a minecraft:jack_o_lantern 1
give @a minecraft:jigsaw 1
give @a minecraft:jukebox 1
give @a minecraft:jungle_boat 1
give @a minecraft:jungle_button 1
give @a minecraft:jungle_chest_boat 1
give @a minecraft:jungle_door 1
give @a minecraft:jungle_fence 1
give @a minecraft:jungle_fence_gate 1
give @a minecraft:jungle_leaves 1
give @a minecraft:jungle_log 1
give @a minecraft:jungle_planks 1
give @a minecraft:jungle_pressure_plate 1
give @a minecraft:jungle_sapling 1
give @a minecraft:jungle_sign 1
give @a minecraft:jungle_slab 1
give @a minecraft:jungle_stairs 1
give @a minecraft:jungle_trapdoor 1
give @a minecraft:jungle_wood 1
give @a minecraft:kelp 1
give @a minecraft:knowledge_book 1
give @a minecraft:ladder 1
give @a minecraft:lantern 1
give @a minecraft:lapis_block 1
give @a minecraft:lapis_lazuli 1
give @a minecraft:lapis_ore 1
give @a minecraft:large_amethyst_bud 1
give @a minecraft:large_fern 1
give @a minecraft:lava_bucket 1
give @a minecraft:lead 1
give @a minecraft:leather 1
give @a minecraft:leather_boots 1
give @a minecraft:leather_chestplate 1
give @a minecraft:leather_helmet 1
give @a minecraft:leather_horse_armor 1
give @a minecraft:leather_leggings 1
give @a minecraft:lectern 1
give @a minecraft:lever 1
give @a minecraft:light 1
give @a minecraft:light_blue_banner 1
give @a minecraft:light_blue_bed 1
give @a minecraft:light_blue_candle 1
give @a minecraft:light_blue_carpet 1
give @a minecraft:light_blue_concrete 1
give @a minecraft:light_blue_concrete_powder 1
give @a minecraft:light_blue_dye 1
give @a minecraft:light_blue_glazed_terracotta 1
give @a minecraft:light_blue_shulker_box 1
give @a minecraft:light_blue_stained_glass 1
give @a minecraft:light_blue_stained_glass_pane 1
give @a minecraft:light_blue_terracotta 1
give @a minecraft:light_blue_wool 1
give @a minecraft:light_gray_banner 1
give @a minecraft:light_gray_bed 1
give @a minecraft:light_gray_candle 1
give @a minecraft:light_gray_carpet 1
give @a minecraft:light_gray_concrete 1
give @a minecraft:light_gray_concrete_powder 1
give @a minecraft:light_gray_dye 1
give @a minecraft:light_gray_glazed_terracotta 1
give @a minecraft:light_gray_shulker_box 1
give @a minecraft:light_gray_stained_glass 1
give @a minecraft:light_gray_stained_glass_pane 1
give @a minecraft:light_gray_terracotta 1
give @a minecraft:light_gray_wool 1
give @a minecraft:light_weighted_pressure_plate 1
give @a minecraft:lightning_rod 1
give @a minecraft:lilac 1
give @a minecraft:lily_of_the_valley 1
give @a minecraft:lily_pad 1
give @a minecraft:lime_banner 1
give @a minecraft:lime_bed 1
give @a minecraft:lime_candle 1
give @a minecraft:lime_carpet 1
give @a minecraft:lime_concrete 1
give @a minecraft:lime_concrete_powder 1
give @a minecraft:lime_dye 1
give @a minecraft:lime_glazed_terracotta 1
give @a minecraft:lime_shulker_box 1
give @a minecraft:lime_stained_glass 1
give @a minecraft:lime_stained_glass_pane 1
give @a minecraft:lime_terracotta 1
give @a minecraft:lime_wool 1
give @a minecraft:lingering_potion 1
give @a minecraft:llama_spawn_egg 1
give @a minecraft:lodestone 1
give @a minecraft:loom 1
give @a minecraft:magenta_banner 1
give @a minecraft:magenta_bed 1
give @a minecraft:magenta_candle 1
give @a minecraft:magenta_carpet 1
give @a minecraft:magenta_concrete 1
give @a minecraft:magenta_concrete_powder 1
give @a minecraft:magenta_dye 1
give @a minecraft:magenta_glazed_terracotta 1
give @a minecraft:magenta_shulker_box 1
give @a minecraft:magenta_stained_glass 1
give @a minecraft:magenta_stained_glass_pane 1
give @a minecraft:magenta_terracotta 1
give @a minecraft:magenta_wool 1
give @a minecraft:magma_block 1
give @a minecraft:magma_cream 1
give @a minecraft:magma_cube_spawn_egg 1
give @a minecraft:mangrove_boat 1
give @a minecraft:mangrove_button 1
give @a minecraft:mangrove_chest_boat 1
give @a minecraft:mangrove_door 1
give @a minecraft:mangrove_fence 1
give @a minecraft:mangrove_fence_gate 1
give @a minecraft:mangrove_leaves 1
give @a minecraft:mangrove_log 1
give @a minecraft:mangrove_planks 1
give @a minecraft:mangrove_pressure_plate 1
give @a minecraft:mangrove_propagule 1
give @a minecraft:mangrove_roots 1
give @a minecraft:mangrove_sign 1
give @a minecraft:mangrove_slab 1
give @a minecraft:mangrove_stairs 1
give @a minecraft:mangrove_trapdoor 1
give @a minecraft:mangrove_wood 1
give @a minecraft:map 1
give @a minecraft:medium_amethyst_bud 1
give @a minecraft:melon 1
give @a minecraft:melon_seeds 1
give @a minecraft:melon_slice 1
give @a minecraft:milk_bucket 1
give @a minecraft:minecart 1
give @a minecraft:mojang_banner_pattern 1
give @a minecraft:mooshroom_spawn_egg 1
give @a minecraft:moss_block 1
give @a minecraft:moss_carpet 1
give @a minecraft:mossy_cobblestone 1
give @a minecraft:mossy_cobblestone_slab 1
give @a minecraft:mossy_cobblestone_stairs 1
give @a minecraft:mossy_cobblestone_wall 1
give @a minecraft:mossy_stone_brick_slab 1
give @a minecraft:mossy_stone_brick_stairs 1
give @a minecraft:mossy_stone_brick_wall 1
give @a minecraft:mossy_stone_bricks 1
give @a minecraft:mud 1
give @a minecraft:mud_brick_slab 1
give @a minecraft:mud_brick_stairs 1
give @a minecraft:mud_brick_wall 1
give @a minecraft:mud_bricks 1
give @a minecraft:muddy_mangrove_roots 1
give @a minecraft:mule_spawn_egg 1
give @a minecraft:mushroom_stem 1
give @a minecraft:mushroom_stew 1
give @a minecraft:music_disc_11 1
give @a minecraft:music_disc_13 1
give @a minecraft:music_disc_5 1
give @a minecraft:music_disc_blocks 1
give @a minecraft:music_disc_cat 1
give @a minecraft:music_disc_chirp 1
give @a minecraft:music_disc_far 1
give @a minecraft:music_disc_mall 1
give @a minecraft:music_disc_mellohi 1
give @a minecraft:music_disc_otherside 1
give @a minecraft:music_disc_pigstep 1
give @a minecraft:music_disc_stal 1
give @a minecraft:music_disc_strad 1
give @a minecraft:music_disc_wait 1
give @a minecraft:music_disc_ward 1
give @a minecraft:mutton 1
give @a minecraft:mycelium 1
give @a minecraft:name_tag 1
give @a minecraft:nautilus_shell 1
give @a minecraft:nether_brick 1
give @a minecraft:nether_brick_fence 1
give @a minecraft:nether_brick_slab 1
give @a minecraft:nether_brick_stairs 1
give @a minecraft:nether_brick_wall 1
give @a minecraft:nether_bricks 1
give @a minecraft:nether_gold_ore 1
give @a minecraft:nether_quartz_ore 1
give @a minecraft:nether_sprouts 1
give @a minecraft:nether_star 1
give @a minecraft:nether_wart 1
give @a minecraft:nether_wart_block 1
give @a minecraft:netherite_axe 1
give @a minecraft:netherite_block 1
give @a minecraft:netherite_boots 1
give @a minecraft:netherite_chestplate 1
give @a minecraft:netherite_helmet 1
give @a minecraft:netherite_hoe 1
give @a minecraft:netherite_ingot 1
give @a minecraft:netherite_leggings 1
give @a minecraft:netherite_pickaxe 1
give @a minecraft:netherite_scrap 1
give @a minecraft:netherite_shovel 1
give @a minecraft:netherite_sword 1
give @a minecraft:netherrack 1
give @a minecraft:note_block 1
give @a minecraft:oak_boat 1
give @a minecraft:oak_button 1
give @a minecraft:oak_chest_boat 1
give @a minecraft:oak_door 1
give @a minecraft:oak_fence 1
give @a minecraft:oak_fence_gate 1
give @a minecraft:oak_leaves 1
give @a minecraft:oak_log 1
give @a minecraft:oak_planks 1
give @a minecraft:oak_pressure_plate 1
give @a minecraft:oak_sapling 1
give @a minecraft:oak_sign 1
give @a minecraft:oak_slab 1
give @a minecraft:oak_stairs 1
give @a minecraft:oak_trapdoor 1
give @a minecraft:oak_wood 1
give @a minecraft:observer 1
give @a minecraft:obsidian 1
give @a minecraft:ocelot_spawn_egg 1
give @a minecraft:ochre_froglight 1
give @a minecraft:orange_banner 1
give @a minecraft:orange_bed 1
give @a minecraft:orange_candle 1
give @a minecraft:orange_carpet 1
give @a minecraft:orange_concrete 1
give @a minecraft:orange_concrete_powder 1
give @a minecraft:orange_dye 1
give @a minecraft:orange_glazed_terracotta 1
give @a minecraft:orange_shulker_box 1
give @a minecraft:orange_stained_glass 1
give @a minecraft:orange_stained_glass_pane 1
give @a minecraft:orange_terracotta 1
give @a minecraft:orange_tulip 1
give @a minecraft:orange_wool 1
give @a minecraft:oxeye_daisy 1
give @a minecraft:oxidized_copper 1
give @a minecraft:oxidized_cut_copper 1
give @a minecraft:oxidized_cut_copper_slab 1
give @a minecraft:oxidized_cut_copper_stairs 1
give @a minecraft:packed_ice 1
give @a minecraft:packed_mud 1
give @a minecraft:painting 1
give @a minecraft:panda_spawn_egg 1
give @a minecraft:paper 1
give @a minecraft:parrot_spawn_egg 1
give @a minecraft:pearlescent_froglight 1
give @a minecraft:peony 1
give @a minecraft:petrified_oak_slab 1
give @a minecraft:phantom_membrane 1
give @a minecraft:phantom_spawn_egg 1
give @a minecraft:pig_spawn_egg 1
give @a minecraft:piglin_banner_pattern 1
give @a minecraft:piglin_brute_spawn_egg 1
give @a minecraft:piglin_spawn_egg 1
give @a minecraft:pillager_spawn_egg 1
give @a minecraft:pink_banner 1
give @a minecraft:pink_bed 1
give @a minecraft:pink_candle 1
give @a minecraft:pink_carpet 1
give @a minecraft:pink_concrete 1
give @a minecraft:pink_concrete_powder 1
give @a minecraft:pink_dye 1
give @a minecraft:pink_glazed_terracotta 1
give @a minecraft:pink_shulker_box 1
give @a minecraft:pink_stained_glass 1
give @a minecraft:pink_stained_glass_pane 1
give @a minecraft:pink_terracotta 1
give @a minecraft:pink_tulip 1
give @a minecraft:pink_wool 1
give @a minecraft:piston 1
give @a minecraft:player_head 1
give @a minecraft:podzol 1
give @a minecraft:pointed_dripstone 1
give @a minecraft:poisonous_potato 1
give @a minecraft:polar_bear_spawn_egg 1
give @a minecraft:polished_andesite 1
give @a minecraft:polished_andesite_slab 1
give @a minecraft:polished_andesite_stairs 1
give @a minecraft:polished_basalt 1
give @a minecraft:polished_blackstone 1
give @a minecraft:polished_blackstone_brick_slab 1
give @a minecraft:polished_blackstone_brick_stairs 1
give @a minecraft:polished_blackstone_brick_wall 1
give @a minecraft:polished_blackstone_bricks 1
give @a minecraft:polished_blackstone_button 1
give @a minecraft:polished_blackstone_pressure_plate 1
give @a minecraft:polished_blackstone_slab 1
give @a minecraft:polished_blackstone_stairs 1
give @a minecraft:polished_blackstone_wall 1
give @a minecraft:polished_deepslate 1
give @a minecraft:polished_deepslate_slab 1
give @a minecraft:polished_deepslate_stairs 1
give @a minecraft:polished_deepslate_wall 1
give @a minecraft:polished_diorite 1
give @a minecraft:polished_diorite_slab 1
give @a minecraft:polished_diorite_stairs 1
give @a minecraft:polished_granite 1
give @a minecraft:polished_granite_slab 1
give @a minecraft:polished_granite_stairs 1
give @a minecraft:popped_chorus_fruit 1
give @a minecraft:poppy 1
give @a minecraft:porkchop 1
give @a minecraft:potato 1
give @a minecraft:potion 1
give @a minecraft:powder_snow_bucket 1
give @a minecraft:powered_rail 1
give @a minecraft:prismarine 1
give @a minecraft:prismarine_brick_slab 1
give @a minecraft:prismarine_brick_stairs 1
give @a minecraft:prismarine_bricks 1
give @a minecraft:prismarine_crystals 1
give @a minecraft:prismarine_shard 1
give @a minecraft:prismarine_slab 1
give @a minecraft:prismarine_stairs 1
give @a minecraft:prismarine_wall 1
give @a minecraft:pufferfish 1
give @a minecraft:pufferfish_bucket 1
give @a minecraft:pufferfish_spawn_egg 1
give @a minecraft:pumpkin 1
give @a minecraft:pumpkin_pie 1
give @a minecraft:pumpkin_seeds 1
give @a minecraft:purple_banner 1
give @a minecraft:purple_bed 1
give @a minecraft:purple_candle 1
give @a minecraft:purple_carpet 1
give @a minecraft:purple_concrete 1
give @a minecraft:purple_concrete_powder 1
give @a minecraft:purple_dye 1
give @a minecraft:purple_glazed_terracotta 1
give @a minecraft:purple_shulker_box 1
give @a minecraft:purple_stained_glass 1
give @a minecraft:purple_stained_glass_pane 1
give @a minecraft:purple_terracotta 1
give @a minecraft:purple_wool 1
give @a minecraft:purpur_block 1
give @a minecraft:purpur_pillar 1
give @a minecraft:purpur_slab 1
give @a minecraft:purpur_stairs 1
give @a minecraft:quartz 1
give @a minecraft:quartz_block 1
give @a minecraft:quartz_bricks 1
give @a minecraft:quartz_pillar 1
give @a minecraft:quartz_slab 1
give @a minecraft:quartz_stairs 1
give @a minecraft:rabbit 1
give @a minecraft:rabbit_foot 1
give @a minecraft:rabbit_hide 1
give @a minecraft:rabbit_spawn_egg 1
give @a minecraft:rabbit_stew 1
give @a minecraft:rail 1
give @a minecraft:ravager_spawn_egg 1
give @a minecraft:raw_copper 1
give @a minecraft:raw_copper_block 1
give @a minecraft:raw_gold 1
give @a minecraft:raw_gold_block 1
give @a minecraft:raw_iron 1
give @a minecraft:raw_iron_block 1
give @a minecraft:recovery_compass 1
give @a minecraft:red_banner 1
give @a minecraft:red_bed 1
give @a minecraft:red_candle 1
give @a minecraft:red_carpet 1
give @a minecraft:red_concrete 1
give @a minecraft:red_concrete_powder 1
give @a minecraft:red_dye 1
give @a minecraft:red_glazed_terracotta 1
give @a minecraft:red_mushroom 1
give @a minecraft:red_mushroom_block 1
give @a minecraft:red_nether_brick_slab 1
give @a minecraft:red_nether_brick_stairs 1
give @a minecraft:red_nether_brick_wall 1
give @a minecraft:red_nether_bricks 1
give @a minecraft:red_sand 1
give @a minecraft:red_sandstone 1
give @a minecraft:red_sandstone_slab 1
give @a minecraft:red_sandstone_stairs 1
give @a minecraft:red_sandstone_wall 1
give @a minecraft:red_shulker_box 1
give @a minecraft:red_stained_glass 1
give @a minecraft:red_stained_glass_pane 1
give @a minecraft:red_terracotta 1
give @a minecraft:red_tulip 1
give @a minecraft:red_wool 1
give @a minecraft:redstone 1
give @a minecraft:redstone_block 1
give @a minecraft:redstone_lamp 1
give @a minecraft:redstone_ore 1
give @a minecraft:redstone_torch 1
give @a minecraft:reinforced_deepslate 1
give @a minecraft:repeater 1
give @a minecraft:repeating_command_block 1
give @a minecraft:respawn_anchor 1
give @a minecraft:rooted_dirt 1
give @a minecraft:rose_bush 1
give @a minecraft:rotten_flesh 1
give @a minecraft:saddle 1
give @a minecraft:salmon 1
give @a minecraft:salmon_bucket 1
give @a minecraft:salmon_spawn_egg 1
give @a minecraft:sand 1
give @a minecraft:sandstone 1
give @a minecraft:sandstone_slab 1
give @a minecraft:sandstone_stairs 1
give @a minecraft:sandstone_wall 1
give @a minecraft:scaffolding 1
give @a minecraft:sculk 1
give @a minecraft:sculk_catalyst 1
give @a minecraft:sculk_sensor 1
give @a minecraft:sculk_shrieker 1
give @a minecraft:sculk_vein 1
give @a minecraft:scute 1
give @a minecraft:sea_lantern 1
give @a minecraft:sea_pickle 1
give @a minecraft:seagrass 1
give @a minecraft:shears 1
give @a minecraft:sheep_spawn_egg 1
give @a minecraft:shield 1
give @a minecraft:shroomlight 1
give @a minecraft:shulker_box 1
give @a minecraft:shulker_shell 1
give @a minecraft:shulker_spawn_egg 1
give @a minecraft:silverfish_spawn_egg 1
give @a minecraft:skeleton_horse_spawn_egg 1
give @a minecraft:skeleton_skull 1
give @a minecraft:skeleton_spawn_egg 1
give @a minecraft:skull_banner_pattern 1
give @a minecraft:slime_ball 1
give @a minecraft:slime_block 1
give @a minecraft:slime_spawn_egg 1
give @a minecraft:small_amethyst_bud 1
give @a minecraft:small_dripleaf 1
give @a minecraft:smithing_table 1
give @a minecraft:smoker 1
give @a minecraft:smooth_basalt 1
give @a minecraft:smooth_quartz 1
give @a minecraft:smooth_quartz_slab 1
give @a minecraft:smooth_quartz_stairs 1
give @a minecraft:smooth_red_sandstone 1
give @a minecraft:smooth_red_sandstone_slab 1
give @a minecraft:smooth_red_sandstone_stairs 1
give @a minecraft:smooth_sandstone 1
give @a minecraft:smooth_sandstone_slab 1
give @a minecraft:smooth_sandstone_stairs 1
give @a minecraft:smooth_stone 1
give @a minecraft:smooth_stone_slab 1
give @a minecraft:snow 1
give @a minecraft:snow_block 1
give @a minecraft:snowball 1
give @a minecraft:soul_campfire 1
give @a minecraft:soul_lantern 1
give @a minecraft:soul_sand 1
give @a minecraft:soul_soil 1
give @a minecraft:soul_torch 1
give @a minecraft:spawner 1
give @a minecraft:spectral_arrow 1
give @a minecraft:spider_eye 1
give @a minecraft:spider_spawn_egg 1
give @a minecraft:splash_potion 1
give @a minecraft:sponge 1
give @a minecraft:spore_blossom 1
give @a minecraft:spruce_boat 1
give @a minecraft:spruce_button 1
give @a minecraft:spruce_chest_boat 1
give @a minecraft:spruce_door 1
give @a minecraft:spruce_fence 1
give @a minecraft:spruce_fence_gate 1
give @a minecraft:spruce_leaves 1
give @a minecraft:spruce_log 1
give @a minecraft:spruce_planks 1
give @a minecraft:spruce_pressure_plate 1
give @a minecraft:spruce_sapling 1
give @a minecraft:spruce_sign 1
give @a minecraft:spruce_slab 1
give @a minecraft:spruce_stairs 1
give @a minecraft:spruce_trapdoor 1
give @a minecraft:spruce_wood 1
give @a minecraft:spyglass 1
give @a minecraft:squid_spawn_egg 1
give @a minecraft:stick 1
give @a minecraft:sticky_piston 1
give @a minecraft:stone 1
give @a minecraft:stone_axe 1
give @a minecraft:stone_brick_slab 1
give @a minecraft:stone_brick_stairs 1
give @a minecraft:stone_brick_wall 1
give @a minecraft:stone_bricks 1
give @a minecraft:stone_button 1
give @a minecraft:stone_hoe 1
give @a minecraft:stone_pickaxe 1
give @a minecraft:stone_pressure_plate 1
give @a minecraft:stone_shovel 1
give @a minecraft:stone_slab 1
give @a minecraft:stone_stairs 1
give @a minecraft:stone_sword 1
give @a minecraft:stonecutter 1
give @a minecraft:stray_spawn_egg 1
give @a minecraft:strider_spawn_egg 1
give @a minecraft:string 1
give @a minecraft:stripped_acacia_log 1
give @a minecraft:stripped_acacia_wood 1
give @a minecraft:stripped_birch_log 1
give @a minecraft:stripped_birch_wood 1
give @a minecraft:stripped_crimson_hyphae 1
give @a minecraft:stripped_crimson_stem 1
give @a minecraft:stripped_dark_oak_log 1
give @a minecraft:stripped_dark_oak_wood 1
give @a minecraft:stripped_jungle_log 1
give @a minecraft:stripped_jungle_wood 1
give @a minecraft:stripped_mangrove_log 1
give @a minecraft:stripped_mangrove_wood 1
give @a minecraft:stripped_oak_log 1
give @a minecraft:stripped_oak_wood 1
give @a minecraft:stripped_spruce_log 1
give @a minecraft:stripped_spruce_wood 1
give @a minecraft:stripped_warped_hyphae 1
give @a minecraft:stripped_warped_stem 1
give @a minecraft:structure_block 1
give @a minecraft:structure_void 1
give @a minecraft:sugar 1
give @a minecraft:sugar_cane 1
give @a minecraft:sunflower 1
give @a minecraft:suspicious_stew 1
give @a minecraft:sweet_berries 1
give @a minecraft:tadpole_bucket 1
give @a minecraft:tadpole_spawn_egg 1
give @a minecraft:tall_grass 1
give @a minecraft:target 1
give @a minecraft:terracotta 1
give @a minecraft:tinted_glass 1
give @a minecraft:tipped_arrow 1
give @a minecraft:tnt 1
give @a minecraft:tnt_minecart 1
give @a minecraft:torch 1
give @a minecraft:totem_of_undying 1
give @a minecraft:trader_llama_spawn_egg 1
give @a minecraft:trapped_chest 1
give @a minecraft:trident 1
give @a minecraft:tripwire_hook 1
give @a minecraft:tropical_fish 1
give @a minecraft:tropical_fish_bucket 1
give @a minecraft:tropical_fish_spawn_egg 1
give @a minecraft:tube_coral 1
give @a minecraft:tube_coral_block 1
give @a minecraft:tube_coral_fan 1
give @a minecraft:tuff 1
give @a minecraft:turtle_egg 1
give @a minecraft:turtle_helmet 1
give @a minecraft:turtle_spawn_egg 1
give @a minecraft:twisting_vines 1
give @a minecraft:verdant_froglight 1
give @a minecraft:vex_spawn_egg 1
give @a minecraft:villager_spawn_egg 1
give @a minecraft:vindicator_spawn_egg 1
give @a minecraft:vine 1
give @a minecraft:wandering_trader_spawn_egg 1
give @a minecraft:warden_spawn_egg 1
give @a minecraft:warped_button 1
give @a minecraft:warped_door 1
give @a minecraft:warped_fence 1
give @a minecraft:warped_fence_gate 1
give @a minecraft:warped_fungus 1
give @a minecraft:warped_fungus_on_a_stick 1
give @a minecraft:warped_hyphae 1
give @a minecraft:warped_nylium 1
give @a minecraft:warped_planks 1
give @a minecraft:warped_pressure_plate 1
give @a minecraft:warped_roots 1
give @a minecraft:warped_sign 1
give @a minecraft:warped_slab 1
give @a minecraft:warped_stairs 1
give @a minecraft:warped_stem 1
give @a minecraft:warped_trapdoor 1
give @a minecraft:warped_wart_block 1
give @a minecraft:water_bucket 1
give @a minecraft:waxed_copper_block 1
give @a minecraft:waxed_cut_copper 1
give @a minecraft:waxed_cut_copper_slab 1
give @a minecraft:waxed_cut_copper_stairs 1
give @a minecraft:waxed_exposed_copper 1
give @a minecraft:waxed_exposed_cut_copper 1
give @a minecraft:waxed_exposed_cut_copper_slab 1
give @a minecraft:waxed_exposed_cut_copper_stairs 1
give @a minecraft:waxed_oxidized_copper 1
give @a minecraft:waxed_oxidized_cut_copper 1
give @a minecraft:waxed_oxidized_cut_copper_slab 1
give @a minecraft:waxed_oxidized_cut_copper_stairs 1
give @a minecraft:waxed_weathered_copper 1
give @a minecraft:waxed_weathered_cut_copper 1
give @a minecraft:waxed_weathered_cut_copper_slab 1
give @a minecraft:waxed_weathered_cut_copper_stairs 1
give @a minecraft:weathered_copper 1
give @a minecraft:weathered_cut_copper 1
give @a minecraft:weathered_cut_copper_slab 1
give @a minecraft:weathered_cut_copper_stairs 1
give @a minecraft:weeping_vines 1
give @a minecraft:wet_sponge 1
give @a minecraft:wheat 1
give @a minecraft:wheat_seeds 1
give @a minecraft:white_banner 1
give @a minecraft:white_bed 1
give @a minecraft:white_candle 1
give @a minecraft:white_carpet 1
give @a minecraft:white_concrete 1
give @a minecraft:white_concrete_powder 1
give @a minecraft:white_dye 1
give @a minecraft:white_glazed_terracotta 1
give @a minecraft:white_shulker_box 1
give @a minecraft:white_stained_glass 1
give @a minecraft:white_stained_glass_pane 1
give @a minecraft:white_terracotta 1
give @a minecraft:white_tulip 1
give @a minecraft:white_wool 1
give @a minecraft:witch_spawn_egg 1
give @a minecraft:wither_rose 1
give @a minecraft:wither_skeleton_skull 1
give @a minecraft:wither_skeleton_spawn_egg 1
give @a minecraft:wolf_spawn_egg 1
give @a minecraft:wooden_axe 1
give @a minecraft:wooden_hoe 1
give @a minecraft:wooden_pickaxe 1
give @a minecraft:wooden_shovel 1
give @a minecraft:wooden_sword 1
give @a minecraft:writable_book 1
give @a minecraft:written_book 1
give @a minecraft:yellow_banner 1
give @a minecraft:yellow_bed 1
give @a minecraft:yellow_candle 1
give @a minecraft:yellow_carpet 1
give @a minecraft:yellow_concrete 1
give @a minecraft:yellow_concrete_powder 1
give @a minecraft:yellow_dye 1
give @a minecraft:yellow_glazed_terracotta 1
give @a minecraft:yellow_shulker_box 1
give @a minecraft:yellow_stained_glass 1
give @a minecraft:yellow_stained_glass_pane 1
give @a minecraft:yellow_terracotta 1
give @a minecraft:yellow_wool 1
give @a minecraft:zoglin_spawn_egg 1
give @a minecraft:zombie_head 1
give @a minecraft:zombie_horse_spawn_egg 1
give @a minecraft:zombie_spawn_egg 1
give @a minecraft:zombie_villager_spawn_egg 1
give @a minecraft:zombified_piglin_spawn_egg 1
